DROP TABLE TM_SERVICE_AVAILABILITY_CHECK IF EXISTS;
   CREATE TABLE TM_SERVICE_AVAILABILITY_CHECK
   (
   RESOURCE_INST_ID VARCHAR(50) NOT NULL,
   POSTCODE VARCHAR(6) NOT NULL,
   STREET_TYPE VARCHAR(50) NOT NULL,
   STREET_NAME VARCHAR(500) NOT NULL,
   BUILDING_NAME VARCHAR(500), 
   FLOOR_NUMBER VARCHAR(10) ,
   HOUSE_UNIT_LOT VARCHAR(10) NOT NULL,
   COUNTRY VARCHAR(50) NOT NULL,
   STATE VARCHAR(50) NOT NULL,
   CITY VARCHAR(50) NOT NULL,
   SECTION VARCHAR(50) NOT NULL 
   
   );
   
   