//ADDRESS SERVICEABILITY 
INSERT INTO TM_SERVICE_AVAILABILITY_CHECK VALUES ('10000', '50000', 'JALAN', 'BUKIT BINTANG', 'THE WESTIN', '37', '3406', 'MALAYSIA', 'KUALA LUMPUR', 'KUALA LUMPUR', 'SECTION 1');
INSERT INTO TM_SERVICE_AVAILABILITY_CHECK VALUES ('10001', '50000', 'JALAN', 'BUKIT BINTANG', 'THE WESTIN', '38', '3506', 'MALAYSIA', 'KUALA LUMPUR', 'KUALA LUMPUR', 'SECTION 1');
INSERT INTO TM_SERVICE_AVAILABILITY_CHECK VALUES ('10002', '50000', 'JALAN', 'BUKIT BINTANG', 'THE WESTIN', '36', '3606', 'MALAYSIA', 'KUALA LUMPUR', 'KUALA LUMPUR', 'SECTION 1');
INSERT INTO TM_SERVICE_AVAILABILITY_CHECK VALUES ('10003', '50000', 'JALAN', 'BUKIT BINTANG', 'THE WESTIN', '35', '3507', 'MALAYSIA', 'KUALA LUMPUR', 'KUALA LUMPUR', 'SECTION 1');
INSERT INTO TM_SERVICE_AVAILABILITY_CHECK VALUES ('10004', '50001', 'JALAN', 'TUN ISMAIL', NULL, NULL, '1', 'MALAYSIA', 'SABAH', 'SABAH', 'SECTION 2');
-- high rise without building name
INSERT INTO TM_SERVICE_AVAILABILITY_CHECK VALUES ('10005', '50001', 'JALAN', 'TUN ISMAIL', NULL, '15', '2', 'MALAYSIA', 'SABAH', 'SABAH', 'SECTION 2');
INSERT INTO TM_SERVICE_AVAILABILITY_CHECK VALUES ('10006', '50001', 'JALAN', 'TUN ISMAIL', 'THE MARRIOTT', '10', '1001', 'MALAYSIA', 'SABAH', 'SABAH', 'SECTION 2');